# Default values for infocenter.
namespace: infocenter
infocenterVersion: 2024-09
replicaCount: 1

image:
  repository: eclipsecbi/eclipse-infocenter
  pullPolicy: IfNotPresent
  tag: "2024-09@sha256:4f69aeaddf026cabc00a10933e0a0811dcbd8ecd2bff68e6f4e53ea1ebb9f536"

service:
  type: ClusterIP
  port: 80
  targetPort: 8086

route:
  host: help.eclipse.org

affinity: {}
