# Default values for infocenter.

namespace: infocenter
infocenterVersion: 2022-03
replicaCount: 1

image:
  repository: eclipsecbi/eclipse-infocenter
  pullPolicy: IfNotPresent
  tag: "2022-03@sha256:fce4917508e39fe9b74fd5d309a952669890d44b107f99bbc632744683d5d880"

service:
  type: ClusterIP
  port: 80
  targetPort: 8086

route:
  host: help.eclipse.org

affinity: {}
