# Default values for infocenter.

namespace: infocenter
infocenterVersion: 2022-09
replicaCount: 1

image:
  repository: eclipsecbi/eclipse-infocenter
  pullPolicy: IfNotPresent
  tag: "2022-09@sha256:a4e4074170c8781dd353eb9b38c6cbe5dd78eafa13ce6cd23307e29b8d8aeba2"

service:
  type: ClusterIP
  port: 80
  targetPort: 8086

route:
  host: help.eclipse.org

affinity: {}
