# Default values for infocenter.
namespace: infocenter
infocenterVersion: 2023-12
replicaCount: 1

image:
  repository: eclipsecbi/eclipse-infocenter
  pullPolicy: IfNotPresent
  tag: "2023-12@sha256:a9c5e3bff6f936615b288b169c5f8772ef49e3cb29fa675e24d84d32658006e8"

service:
  type: ClusterIP
  port: 80
  targetPort: 8086

route:
  host: help.eclipse.org

affinity: {}
