# Default values for infocenter.
namespace: infocenter
infocenterVersion: 2025-03
replicaCount: 1

image:
  repository: eclipsecbi/eclipse-infocenter
  pullPolicy: IfNotPresent
  tag: "2025-03@sha256:27331c06a61fa4006995e187e17e6846cade01ff0eb941b2921200072c03c1cd"

service:
  type: ClusterIP
  port: 80
  targetPort: 8086

route:
  host: help.eclipse.org

affinity: {}
