# Default values for infocenter.

namespace: infocenter
infocenterVersion: 2022-06
replicaCount: 1

image:
  repository: eclipsecbi/eclipse-infocenter
  pullPolicy: IfNotPresent
  tag: "2022-06@sha256:d41616e26f077272a96a8cf7df3431e92c80ad4e2b544393a6477cbb0d63649b"

service:
  type: ClusterIP
  port: 80
  targetPort: 8086

route:
  host: help.eclipse.org

affinity: {}
