# Default values for infocenter.
namespace: infocenter
infocenterVersion: 2024-06
replicaCount: 1

image:
  repository: eclipsecbi/eclipse-infocenter
  pullPolicy: IfNotPresent
  tag: "2024-06@sha256:7dbdd19f59095fb780f74be04c82f8e16fb2614779cd98a60a19e6de7ef35929"

service:
  type: ClusterIP
  port: 80
  targetPort: 8086

route:
  host: help.eclipse.org

affinity: {}
