# Default values for infocenter.
namespace: infocenter
infocenterVersion: 2025-06
replicaCount: 1

image:
  repository: eclipsecbi/eclipse-infocenter
  pullPolicy: IfNotPresent
  tag: "2025-06@sha256:f7d8449aba4b64d8e6b40c7d79e58541792799266a769a2b452640209dd65af0"

service:
  type: ClusterIP
  port: 80
  targetPort: 8086

route:
  host: help.eclipse.org

affinity: {}
