# Default values for infocenter.
namespace: infocenter
infocenterVersion: 2025-03
replicaCount: 1

image:
  repository: eclipsecbi/eclipse-infocenter
  pullPolicy: IfNotPresent
  tag: "2025-03@sha256:898048486338f46103b3654e50a8963ec58654ec0293e5ba15964b4c59459912"

service:
  type: ClusterIP
  port: 80
  targetPort: 8086

route:
  host: help.eclipse.org

affinity: {}
