# Default values for infocenter.
namespace: infocenter
infocenterVersion: 2024-03
replicaCount: 1

image:
  repository: eclipsecbi/eclipse-infocenter
  pullPolicy: IfNotPresent
  tag: "2024-03@sha256:d8bcdd8763bd5c4ff2cd1166652d2673cc3a287ed0b46d2fa7b252e408dceaf8"

service:
  type: ClusterIP
  port: 80
  targetPort: 8086

route:
  host: help.eclipse.org

affinity: {}
