# Default values for infocenter.
namespace: infocenter
infocenterVersion: 2024-03
replicaCount: 1

image:
  repository: eclipsecbi/eclipse-infocenter
  pullPolicy: IfNotPresent
  tag: "2024-03@sha256:2cc2df470a463d6f7e75bf65d7f02bab551157788cecd956bfb6f547c87a7231"

service:
  type: ClusterIP
  port: 80
  targetPort: 8086

route:
  host: help.eclipse.org

affinity: {}
