# Default values for infocenter.

namespace: infocenter
infocenterVersion: 2023-03
replicaCount: 1

image:
  repository: eclipsecbi/eclipse-infocenter
  pullPolicy: IfNotPresent
  tag: "2023-03@sha256:2de2cb863071bc9df2d94332504c9cfeb17cd9efb68ca1c3a289576024bba4ab"

service:
  type: ClusterIP
  port: 80
  targetPort: 8086

route:
  host: help.eclipse.org

affinity: {}
