# Default values for infocenter.
namespace: infocenter
infocenterVersion: 2024-09
replicaCount: 1

image:
  repository: eclipsecbi/eclipse-infocenter
  pullPolicy: IfNotPresent
  tag: "2024-09@sha256:dedbd8acec7a304c4ddd2ef30268547a607cd74a5022c8d33b7008666a6c1ef7"

service:
  type: ClusterIP
  port: 80
  targetPort: 8086

route:
  host: help.eclipse.org

affinity: {}
