# Default values for infocenter.
namespace: infocenter
infocenterVersion: 2024-03
replicaCount: 1

image:
  repository: eclipsecbi/eclipse-infocenter
  pullPolicy: IfNotPresent
  tag: "2024-03@sha256:2b16dfc7a50420a931270d7cdc42e2378f972a05f9196ae6835a8cc55d296d90"

service:
  type: ClusterIP
  port: 80
  targetPort: 8086

route:
  host: help.eclipse.org

affinity: {}
