# Default values for infocenter.
namespace: infocenter
infocenterVersion: 2024-12
replicaCount: 1

image:
  repository: eclipsecbi/eclipse-infocenter
  pullPolicy: IfNotPresent
  tag: "2024-12@sha256:d3b42878a9539d66957773dd1fb67dca0e97f7e5c167dc482cc9b4b8efc3cb29"

service:
  type: ClusterIP
  port: 80
  targetPort: 8086

route:
  host: help.eclipse.org

affinity: {}
