# Default values for infocenter.
namespace: infocenter
infocenterVersion: 2024-06
replicaCount: 1

image:
  repository: eclipsecbi/eclipse-infocenter
  pullPolicy: IfNotPresent
  tag: "2024-06@sha256:838b97a5b957c93895065a0dc07614656d097183085eca2212bf1ca7e67fab30"

service:
  type: ClusterIP
  port: 80
  targetPort: 8086

route:
  host: help.eclipse.org

affinity: {}
